// export const REQUEST_UPDATE_BRAND_LISTING_ORDER = 'REQUEST_UPDATE_BRAND_LISTING_ORDER'
// export const SUCCESS_UPDATE_BRAND_LISTING_ORDER = 'SUCCESS_UPDATE_BRAND_LISTING_ORDER'

export const REQUEST_FETCH_SKUS = 'REQUEST_FETCH_SKUS'
export const SUCCESS_FETCH_SKUS = 'SUCCESS_FETCH_SKUS'

export const REQUEST_FETCH_BRANDS = 'REQUEST_FETCH_BRANDS'
export const SUCCESS_FETCH_BRANDS = 'SUCCESS_FETCH_BRANDS'

export const REQUEST_FETCH_LIVE_ORDERS = 'REQUEST_FETCH_LIVE_ORDERS'
export const SUCCESS_FETCH_LIVE_ORDERS = 'SUCCESS_FETCH_LIVE_ORDERS'

export const REQUEST_CREATE_SKU = 'REQUEST_CREATE_SKU'
export const SUCCESS_CREATE_SKU = 'SUCCESS_CREATE_SKU'

// export const REQUEST_FETCH_VOLUME_LIST = 'REQUEST_FETCH_VOLUME_LIST'
// export const SUCCESS_FETCH_VOLUME_LIST = 'SUCCESS_FETCH_VOLUME_LIST'

// export const REQUEST_UPDATE_SKU = 'REQUEST_UPDATE_SKU' 
// export const SUCCESS_UPDATE_SKU = 'SUCCESS_UPDATE_SKU'

export const REQUEST_UPDATE_SKU_STATE_MAP = 'REQUEST_UPDATE_SKU_STATE_MAP'
export const SUCCESS_UPDATE_SKU_STATE_MAP = 'SUCCESS_UPDATE_SKU_STATE_MAP'

export const REQUEST_FETCH_STATES_MAPPED_TO_SKU = 'REQUEST_FETCH_STATES_MAPPED_TO_SKU'
export const SUCCESS_FETCH_STATES_MAPPED_TO_SKU = 'SUCCESS_FETCH_STATES_MAPPED_TO_SKU'

export const REQUEST_FETCH_UNMAPPED_STATES = 'REQUEST_FETCH_UNMAPPED_STATES'
export const SUCCESS_FETCH_UNMAPPED_STATES = 'SUCCESS_FETCH_UNMAPPED_STATES'

export const REQUEST_MAP_STATE_TO_SKU = 'REQUEST_FETCH_MAP_STATE_TO_SKU'
export const SUCCESS_MAP_STATE_TO_SKU = 'SUCCESS_MAP_STATE_TO_SKU'

export const REQUEST_FETCH_RETAILERS_MAPPED_TO_SKU = 'REQUEST_FETCH_RETAILERS_MAPPED_TO_SKU'
export const SUCCESS_FETCH_RETAILERS_MAPPED_TO_SKU = 'SUCCESS_FETCH_RETAILERS_MAPPED_TO_SKU'

export const REQUEST_FETCH_SKU_UNMAPPED_RETAILERS = 'REQUEST_FETCH_SKU_UNMAPPED_RETAILERS'
export const SUCCESS_FETCH_SKU_UNMAPPED_RETAILERS = 'SUCCESS_FETCH_SKU_UNMAPPED_RETAILERS'

export const REQUEST_UPDATE_SKU_RETAILER_MAP = 'REQUEST_UPDATE_SKU_RETAILER_MAP'
export const SUCCESS_UPDATE_SKU_RETAILER_MAP = 'SUCCESS_UPDATE_SKU_RETAILER_MAP'

export const REQUEST_MAP_RETAILER_TO_SKU = 'REQUEST_MAP_RETAILER_TO_SKU'
export const SUCCESS_MAP_RETAILER_TO_SKU = 'SUCCESS_MAP_RETAILER_TO_SKU'

// export const REQUEST_FETCH_CATEGORIES = 'REQUEST_FETCH_CATEGORIES'
// export const SUCCESS_FETCH_CATEGORIES = 'SUCCESS_FETCH_CATEGORIES'

// export const REQUEST_CREATE_CATEGORY = 'REQUEST_CREATE_CATEGORY'
// export const SUCCESS_CREATE_CATEGORY = 'SUCCESS_CREATE_CATEGORY'

export const REQUEST_FETCH_ORIGIN_LIST = 'REQUEST_FETCH_ORIGIN_LIST'
export const SUCCESS_FETCH_ORIGIN_LIST = 'SUCCESS_FETCH_ORIGIN_LIST'

export const REQUEST_FETCH_BRAND_TYPE_LIST = 'REQUEST_FETCH_BRAND_TYPE_LIST'
export const SUCCESS_FETCH_BRAND_TYPE_LIST = 'SUCCESS_FETCH_BRAND_TYPE_LIST'

export const REQUEST_CREATE_BRAND = 'REQUEST_CREATE_BRAND'
export const SUCCESS_CREATE_BRAND = 'SUCCESS_CREATE_BRAND'

export const REQUEST_UPDATE_BRAND = 'REQUEST_UPDATE_BRAND'
export const SUCCESS_UPDATE_BRAND = 'SUCCESS_UPDATE_BRAND'

// export const REQUEST_FETCH_BRANDS_MAPPED_TO_CATEGORIES = 'REQUEST_FETCH_BRANDS_MAPPED_TO_CATEGORIES'
// export const SUCCESS_FETCH_BRANDS_MAPPED_TO_CATEGORIES = 'SUCCESS_FETCH_BRANDS_MAPPED_TO_CATEGORIES'

// export const REQUEST_FETCH_UNMAPPED_BRAND_LIST = 'REQUEST_FETCH_UNMAPPED_BRAND_LIST'
// export const SUCCESS_FETCH_UNMAPPED_BRAND_LIST = 'SUCCESS_FETCH_UNMAPPED_BRAND_LIST'

// export const REQUEST_FETCH_MAPPED_BRAND_LIST = 'REQUEST_FETCH_MAPPED_BRAND_LIST'
// export const SUCCESS_FETCH_MAPPED_BRAND_LIST = 'SUCCESS_FETCH_MAPPED_BRAND_LIST'

// export const REQUEST_MAP_BRANDS = 'REQUEST_MAP_BRANDS'
// export const SUCCESS_MAP_BRANDS = 'SUCCESS_MAP_BRANDS'

// export const REQUEST_UNMAP_BRANDS = 'REQUEST_UNMAP_BRANDS'
// export const SUCCESS_UNMAP_BRANDS = 'SUCCESS_UNMAP_BRANDS'

// export const REQUEST_UPDATE_CATEGORY = 'REQUEST_UPDATE_CATEGORY'
// export const SUCCESS_UPDATE_CATEGORY = 'SUCCESS_UPDATE_CATEGORY'

// export const REQUEST_FETCH_COMPANIES = 'REQUEST_FETCH_COMPANIES'
// export const SUCCESS_FETCH_COMPANIES = 'SUCCESS_FETCH_COMPANIES'

// export const REQUEST_CREATE_COMPANY = 'REQUEST_CREATE_COMPANY'
// export const SUCCESS_CREATE_COMPANY = 'SUCCESS_CREATE_COMPANY'

// export const REQUEST_UPDATE_COMPANY = 'REQUEST_UPDATE_COMPANY'
// export const SUCCESS_UPDATE_COMPANY = 'SUCCESS_UPDATE_COMPANY'