export const REQUEST_SET_LOADING_STATE = 'REQUEST_SET_LOADING_STATE'
export const SUCCESS_SET_LOADING_STATE = 'SUCCESS_SET_LOADING_STATE'

export const REQUEST_FETCH_SKUS = 'REQUEST_FETCH_SKUS'
export const SUCCESS_FETCH_SKUS = 'SUCCESS_FETCH_SKUS'

export const REQUEST_FETCH_BRANDS = 'REQUEST_FETCH_BRANDS'
export const SUCCESS_FETCH_BRANDS = 'SUCCESS_FETCH_BRANDS'

export const REQUEST_FETCH_ACCESS_LOGS = "REQUEST_FETCH_ACCESS_LOGS"
export const SUCCESS_FETCH_ACCESS_LOGS = "SUCCESS_FETCH_ACCESS_LOGS"

export const REQUEST_GENRE_BASED_BRAND_LIST = "REQUEST_GENRE_BASED_BRAND_LIST"
export const SUCCESS_GENRE_BASED_BRAND_LIST = "SUCCESS_GENRE_BASED_BRAND_LIST"

export const REQUEST_FETCH_BRAND_LIST = 'REQUEST_FETCH_BRAND_LIST'
export const SUCCESS_FETCH_BRAND_LIST = 'SUCCESS_FETCH_BRAND_LIST'

export const REQUEST_FETCH_BRAND_COLLECTION_LIST = 'REQUEST_FETCH_BRAND_COLLECTION_LIST'
export const SUCCESS_FETCH_BRAND_COLLECTION_LIST = 'SUCCESS_FETCH_BRAND_COLLECTION_LIST'

export const REQUEST_UPDATE_BRAND_COLLECTION_STATUS = 'REQUEST_UPDATE_BRAND_COLLECTION_STATUS'
export const SUCCESS_UPDATE_BRAND_COLLECTION_STATUS = 'SUCCESS_UPDATE_BRAND_COLLECTION_STATUS'

export const REQUEST_CREATE_BRAND_COLLECTION = 'REQUEST_CREATE_BRAND_COLLECTION'
export const SUCCESS_CREATE_BRAND_COLLECTION = 'SUCCESS_CREATE_BRAND_COLLECTION'

export const REQUEST_EDIT_BRAND_COLLECTION = 'REQUEST_EDIT_BRAND_COLLECTION'
export const SUCCESS_EDIT_BRAND_COLLECTION = 'SUCCESS_EDIT_BRAND_COLLECTION'

// export const REQUEST_FETCH_COLLECTION_LIST = 'REQUEST_FETCH_COLLECTION_LIST'
// export const SUCCESS_FETCH_COLLECTION_LIST = 'SUCCESS_FETCH_COLLECTION_LIST'

export const REQUEST_FETCH_LIVE_ORDERS = 'REQUEST_FETCH_LIVE_ORDERS'
export const SUCCESS_FETCH_LIVE_ORDERS = 'SUCCESS_FETCH_LIVE_ORDERS'

export const REQUEST_CREATE_SKU = 'REQUEST_CREATE_SKU'
export const SUCCESS_CREATE_SKU = 'SUCCESS_CREATE_SKU'

export const REQUEST_UPDATE_SKU = 'REQUEST_UPDATE_SKU' 
export const SUCCESS_UPDATE_SKU = 'SUCCESS_UPDATE_SKU'

export const REQUEST_UPDATE_SKU_STATUS = 'REQUEST_UPDATE_SKU_STATUS' 
export const SUCCESS_UPDATE_SKU_STATUS = 'SUCCESS_UPDATE_SKU_STATUS'

export const REQUEST_UPDATE_SKU_STATE_MAP = 'REQUEST_UPDATE_SKU_STATE_MAP'
export const SUCCESS_UPDATE_SKU_STATE_MAP = 'SUCCESS_UPDATE_SKU_STATE_MAP'

export const REQUEST_FETCH_STATES_MAPPED_TO_SKU = 'REQUEST_FETCH_STATES_MAPPED_TO_SKU'
export const SUCCESS_FETCH_STATES_MAPPED_TO_SKU = 'SUCCESS_FETCH_STATES_MAPPED_TO_SKU'

export const REQUEST_FETCH_STATES = 'REQUEST_FETCH_STATES'
export const SUCCESS_FETCH_STATES = 'SUCCESS_FETCH_STATES'

export const REQUEST_FETCH_UNMAPPED_STATES = 'REQUEST_FETCH_UNMAPPED_STATES'
export const SUCCESS_FETCH_UNMAPPED_STATES = 'SUCCESS_FETCH_UNMAPPED_STATES'

export const REQUEST_MAP_STATE_TO_SKU = 'REQUEST_FETCH_MAP_STATE_TO_SKU'
export const SUCCESS_MAP_STATE_TO_SKU = 'SUCCESS_MAP_STATE_TO_SKU'

export const REQUEST_FETCH_RETAILERS_MAPPED_TO_SKU = 'REQUEST_FETCH_RETAILERS_MAPPED_TO_SKU'
export const SUCCESS_FETCH_RETAILERS_MAPPED_TO_SKU = 'SUCCESS_FETCH_RETAILERS_MAPPED_TO_SKU'

export const REQUEST_FETCH_SKU_UNMAPPED_RETAILERS = 'REQUEST_FETCH_SKU_UNMAPPED_RETAILERS'
export const SUCCESS_FETCH_SKU_UNMAPPED_RETAILERS = 'SUCCESS_FETCH_SKU_UNMAPPED_RETAILERS'

export const REQUEST_UPDATE_SKU_RETAILER_MAP = 'REQUEST_UPDATE_SKU_RETAILER_MAP'
export const SUCCESS_UPDATE_SKU_RETAILER_MAP = 'SUCCESS_UPDATE_SKU_RETAILER_MAP'

export const REQUEST_MAP_RETAILER_TO_SKU = 'REQUEST_MAP_RETAILER_TO_SKU'
export const SUCCESS_MAP_RETAILER_TO_SKU = 'SUCCESS_MAP_RETAILER_TO_SKU'

export const REQUEST_FETCH_ORIGIN_LIST = 'REQUEST_FETCH_ORIGIN_LIST'
export const SUCCESS_FETCH_ORIGIN_LIST = 'SUCCESS_FETCH_ORIGIN_LIST'

export const REQUEST_FETCH_BRAND_TYPE_LIST = 'REQUEST_FETCH_BRAND_TYPE_LIST'
export const SUCCESS_FETCH_BRAND_TYPE_LIST = 'SUCCESS_FETCH_BRAND_TYPE_LIST'

export const REQUEST_FETCH_COLLECTION = 'REQUEST_FETCH_COLLECTION'
export const SUCCESS_FETCH_COLLECTION = 'SUCCESS_FETCH_COLLECTION'

export const REQUEST_CREATE_BRAND = 'REQUEST_CREATE_BRAND'
export const SUCCESS_CREATE_BRAND = 'SUCCESS_CREATE_BRAND'

export const REQUEST_UPDATE_BRAND = 'REQUEST_UPDATE_BRAND'
export const SUCCESS_UPDATE_BRAND = 'SUCCESS_UPDATE_BRAND'

export const REQUEST_UPDATE_BRAND_STATUS = 'REQUEST_UPDATE_BRAND_STATUS'
export const SUCCESS_UPDATE_BRAND_STATUS = 'SUCCESS_UPDATE_BRAND_STATUS'

export const REQUEST_FETCH_GENRES = 'REQUEST_FETCH_GENRES'
export const SUCCESS_FETCH_GENRES = 'SUCCESS_FETCH_GENRES'

export const REQUEST_FETCH_GENRE_LIST = 'REQUEST_FETCH_GENRE_LIST'
export const SUCCESS_FETCH_GENRE_LIST = 'SUCCESS_FETCH_GENRE_LIST'

export const REQUEST_UPDATE_GENRE_STATUS = 'REQUEST_UPDATE_GENRE_STATUS'
export const SUCCESS_UPDATE_GENRE_STATUS = 'SUCCESS_UPDATE_GENRE_STATUS'

export const REQUEST_UPDATE_COLLECTION_STATUS = 'REQUEST_UPDATE_COLLECTION_STATUS'
export const SUCCESS_UPDATE_COLLECTION_STATUS = 'SUCCESS_UPDATE_COLLECTION_STATUS'

export const REQUEST_CREATE_GENRE = 'REQUEST_CREATE_GENRE'
export const SUCCESS_CREATE_GENRE = 'SUCCESS_CREATE_GENRE'

export const REQUEST_CREATE_COLLECTION = 'REQUEST_CREATE_COLLECTION'
export const SUCCESS_CREATE_COLLECTION = 'SUCCESS_CREATE_COLLECTION'

export const REQUEST_UPDATE_COLLECTION = 'REQUEST_UPDATE_COLLECTION'
export const SUCCESS_UPDATE_COLLECTION = 'SUCCESS_UPDATE_COLLECTION'

export const REQUEST_UPDATE_GENRE = 'REQUEST_UPDATE_GENRE'
export const SUCCESS_UPDATE_GENRE = 'SUCCESS_UPDATE_GENRE'

export const REQUEST_FETCH_BRAND_LISTING_ORDER = "REQUEST_FETCH_BRAND_LISTING_ORDER"
export const SUCCESS_FETCH_BRAND_LISTING_ORDER = "SUCCESS_FETCH_BRAND_LISTING_ORDER"

export const REQUEST_CREATE_OR_UPDATE_BRAND_LISTING_ORDER = "REQUEST_CREATE_OR_UPDATE_BRAND_LISTING_ORDER"
export const SUCCESS_CREATE_OR_UPDATE_BRAND_LISTING_ORDER = "SUCCESS_CREATE_OR_UPDATE_BRAND_LISTING_ORDER"
